#!/bin/bash

f(){
    # sleep 5
    ip link set wlp3s0 down
    pkill iwd
    ip link set wlp3s0 up
    iwctl station wlp3s0 scan
    sv restart chronyd
}
g(){
    f >/dev/null 2>&1
}
g &!
sleep 1
# iwctl station wlp3s0 disconnect
#
# a="jj"
# let x=0
# while [ -n "$a" ];do
#     sleep 1;
#     echo 'try to connect'
#     a=$(timeout 10 iwctl --passphrase ayoub123a station wlp3s0 connect ayoub2)
#     let x=x+1
#     echo "a$x=$a"
#     if [[ $x == 5 ]];then
#         echo "x=$a"
#         sv restart iwd
#     fi
# done
# echo "fin"
# # iwctl station wlp3s0 scan
# sv restart dhcpcd

# # TODO while to connect
# # timeout 10 ping -c 1 8.8.8.8
