#!/bin/bash

# url="https://github.com/jarun/nnn/blob/master/Makefile"
# url="https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/async_lib/async.lua"
url=${1-}
[[ ! -z $url ]] || exit

# sed not alow to match group > 9, so bettre way is split it
# dash - , should be at end or begin
user_repo="$(sed -E -e 's#((git|ssh|http(s)?)|(git@[\w\.]+))(://)?(([\w\.@\:/\-~])[^/]+)(/|:)##' -e \
    's#(([-a-zA-Z0-9\_\.])+)/(([-a-zA-Z0-9\_\.])+).*#\1/\3#' <<< $url)"
repo=${user_repo#*/}

[[ -z $repo ]] && exit

if [[ ! -d ~/Git/fork/$repo ]]; then
    # todo: git fork manualy to choose depth
    gh repo fork https://github.com/$user_repo --clone=false --org ayoub-fork || exit

    mkdir -p ~/Git/fork && cd $_
    git clone --depth=1 git@github.com:ayoub-fork/$repo
    cd $repo
    git checkout -b patch-1
    sleep 1 && clear
else
    echo '\nAlready you have this directory in your disk and remote'
    cd ~/Git/fork/$repo
fi

file="$(sed -E 's#((git|ssh|http(s)?)|(git@[a-zA-Z0-9\.]+))(://)?(([-a-zA-Z0-9\.@\:/~])[^/]+)(/|:)(([-a-zA-Z0-9\_\.])+/){4}##' <<< $url)"

nvim "$file"
