#!/bin/bash

clear
file=$(git status | awk '/modified:/{print $2}'|fzf)



f(){
    echo "  What should I do with $file ?"
    echo "  s|S|d|D : show Diff"
    echo "  c|C     : commit"
    read CHOICEX
    case $CHOICEX in
        d|D|s|S)
            git diff "$file"
            echo -e '\n------------------\n'
            echo -e 'Press Entre to continue'
            read COMMIT_DIFF
            clear
            case $COMMIT_DIFF in
                c|c)
                    clear
                    echo "  commit message:like up"
                    read commit
                    git add "$file"
                    git commit -m "${commit:-up}"
                    ;;
            esac
            ;;
        c|C)
            echo "  commit message:like up"
            read COMMIT
            git add "$file"
            git commit -m "${COMMIT:-up}"
            ;;
    esac
}
if [[ -n "$file" ]];then
    f
fi

