#!/bin/bash

clear
total=$(git status | awk '/modified:/{print $2}'|wc -l)
file=""



f(){
    clear
    git diff "$file"
    echo -e '\n------------------\n'
    echo "  s|S|d|D : show Diff"
    echo "  c|C     : commit"
    echo "  *       : exit"
    read COMMIT
    case $COMMIT in
        c|C)
            clear
            echo "  commit message:like up"
            read commit
            git add "$file"
            git commit -m "${commit:-up}"
            ;;
        *)
            exit
            ;;
    esac
}
while [[ $total != 0 ]];do
    file=$(git status | awk '/modified:/{print $2}'|fzf)
    if [[ -n "$file" ]];then
        f
    fi
    total=$(git status | awk '/modified:/{print $2}'|wc -l)
done
