#!/bin/bash

clear
total="$(git status | awk '/modified:/{print $2} /renamed:/{print $2}'|wc -l)"
let total=total+$(git status |
    tail --line=+$(echo $(( $(git status | awk '/Untracked files:/{ print NR}') + 2 ))) |
    head --lines=-1 |
    wc -l)
file=""


f(){
    clear
    git diff "$file"
    echo -e '\n------------------\n'
    echo "  s|S|d|D : show Diff"
    echo "  c|C     : commit"
    echo "  v|V     : nvim  "
    echo "  *       : exit"
    read COMMIT
    case $COMMIT in
        c|C)
            clear
            echo "  commit message:like up"
            read commit
            git add "$file"
            git commit -m "${commit:-up}"
            ;;
        v|V)
            clear
            nvim "$file"
            ;;
        *)
            return 0
            ;;
    esac
}
while [[ $total != 0 ]];do
# for i in {1..1};do
    file="$(git status | awk '/modified:/{print $2}')"
    file+="$(git status |
    tail --line=+$(echo $(( $(git status | awk '/Untracked files:/{ print NR}') + 2 ))) |
    head --lines=-1)"
    file="$(echo -e "$file" | sed -E 's/^\s+//g' | tr '\t' '\n'| fzf)"
    if [[ -n "$file" ]];then
        echo "$file: exist"
        f
    fi
    total=$(git status | awk '/modified:/{print $2}'|wc -l)
done

