#!/bin/bash

dir=${1-}

if [[ -z $dir ]];then
    if [[ -f ~/scripts/app/bash-color ]];then
     . ~/scripts/app/bash-color
     yellow '\n\tgit status to the directory:\n'
     red  '$ '
     green    'git_status '
     white  '/path/to/dir\n'
    fi
else
    cd $dir
    git branch
    git status
fi
