#!/bin/bash

clear
file="$1"


f(){
    echo "  What should I do with $file \?"
    echo "  s|S|d|D : show Diff"
    echo "  c|C     : commit"
    read CHOICEX
    case $CHOICEX in
        d|D|s|S)
            git diff "$file"
            echo -e '\n------------------\n'
            echo -e 'Press Entre'
            read X
            clear
            f
            ;;
        c|C)
            echo "  commit message:like up"
            read COMMIT
            git add "$file"
            git commit -m "${COMMIT:-up}"
            ;;
    esac
}
f
