#!/bin/bash
declare -a pkg=""
for i in $*;do
  pkg+="$(cat $i | grep -v '^%' | grep '\\usepackage'| sed -E 's/\%.*//' | sed -E 's#^.*\{(.*)\}#\1#' | tr '\n' ' ')"
done

pkg="$(echo $pkg| tr '\,' '\n' | tr ' ' '\n' | sort| uniq | tr '\n' ' ')"
pkg="$(echo $pkg| sed 's/ +/ /g')"
IFS=', ' read -r -a array <<< "$pkg"

declare -a delete=(
      "already"
      "amssymb"
      "array"
      "fontenc"
      "fullpage"
      "graphicx"
      "hypcap "
      "inputenc"
      "latexsym"
      "lmodern"
      "multicol"
      "tabularx"
      "tikz"
)
for item in ${delete[@]};do
  array=("${array[@]/$item}")
done

declare -a download=(
      "beamertheme-metropolis"
      "adforn"
      "amsfonts"
      "amsmath"
      "babel"
      "booktabs"
      "calculator"
      "caption"
      "enumitem"
      "fancybox"
      "fancyhdr"
      "fontspec"
      "geometry"
      "hyperref"
      "iftex"
      "lastpage"
      "listings"
      "luatextra"
      "makecell"
      "mdframed"
      "mhchem"
      "multirow"
      "natbib"
      "ntheorem"
      "paracol"
      "paralist"
      "parskip"
      "pgfplots"
      "setspace"
      "siunitx"
      "tcolorbox"
      "times"
      "titlesec"
      "titletoc"
      "wrapfig"
      "xcolor"
)

for item in ${download[@]};do
  array=("${array[@]/$item}")
done

array1="$(echo ${array[@]} | sed 's/^ *//')"


if [[ ! -z "${array1}" ]];then
  echo -e "\n\e[93mtlmgr install \e[95m${array1[@]}\e[0m\n"
  tlmgr install ${array[@]}
fi
