#!/bin/bash
declare -a pkg=""
for i in $*;do
  pkg+="$(cat $@ | grep 'usepackage' | sed -E 's#^.*\{(.*)\}#\1#' | tr '\n' ' ')"
done

pkg="$(echo $pkg| tr ' ' '\n' | sort| uniq | tr '\n' ' ')"
pkg="$(echo $pkg| sed 's/ +/ /g')"
IFS=', ' read -r -a array <<< "$pkg"

declare -a delete=(
      "already"
      "amssymb"
      "array"
      "fontenc"
      "fullpage"
      "graphicx"
      "hypcap "
      "inputenc"
      "latexsym"
      "lmodern"
      "multicol"
      "tabularx"
)
for item in ${delete[@]};do
  array=("${array[@]/$item}")
done

declare -a download=(
      "amsfonts"
      "amsmath"
      "babel"
      "fancyhdr"
      "geometry"
      "hyperref"
      "listings"
      "mhchem"
      "multirow"
      "natbib"
      "ntheorem"
      "paralist"
      "siunitx"
      "times"
      "xcolor"
)
for item in ${download[@]};do
  array=("${array[@]/$item}")
done

array1="$(echo ${array[@]} | sed 's/^ *//')"


if [[ ! -z "${array1}" ]];then
  echo -e "\n\e[93mtlmgr install \e[95m${array1[@]}\e[0m\n"
  tlmgr install ${array[@]}
fi
