#!/bin/bash

# e file1.txt

tmpPID="/tmp/nvim_server.pid" && touch  $tmpPID
PID=$(cat /tmp/nvim_server.pid)
PWD=$(pwd)
file="$1"
if [[ -z $tmpPID ]];then
    if ps -p $PID > /dev/null;then
        echo "server run" > /dev/null
    fi
else
# if [ ! -s $tmpPID ]; then
    # kill $(cat $tmpPID)
    # rm -f $tmpPID
    # e $@
    # /tmp/new_tmp/server
    nvim --headless --listen localhost:6666   & echo $! > "$tmpPID"
fi

if [[ -s "$file" && $# == 1 ]];then
    nvim --server localhost:6666 --remote-tab "${PWD}/$file"
else
    echo "not exist"
fi
