#!/bin/bash

# e file1.txt

tmpPID="/tmp/nvim_server.pid"
PID=$(cat /tmp/nvim_server.pid)
file="$1"
PWD=$(pwd)

if ps -p $PID > /dev/null;then
    echo "server run"
else
    nvim --headless --listen localhost:6666   & echo $! > "$tmpPID"
fi

neovide --remote-tcp=localhost:6666
