#!/bin/bash

# how get size of directory

# how path java by export
# or java 8
export JAVA_HOME='/usr/lib/jvm/java-6-openjdk'

#how can i connect to my termux
ssh -p 8022 -i $HOME/.ssh/id_rsa 192.168.1.109
# viw my file in android/termux in server/boid-linux
sshfs anything@192.168.1.109:/data/data/com.termux/files/home/  $HOME/termux -p 8022 -o IdentityFile=$HOME/.ssh/id_rsa

unzip
http://github.com/maxim-saplin/NetCoreStorageSpeedTest/releases/download/2.0.2-u/CPDT_Linux.zip
