#!/bin/bash

# how get size of directory
alias ddd="du -ah --max-depth 1"
# vim load plugin
:runtime! plugin/my_plugin.vim




# :UpdateRemotePlugins
# :checkhealth

# how path java by export
# or java 8
export JAVA_HOME='/usr/lib/jvm/java-6-openjdk'


ssh-keygen -t ed25519 -C "ayoubelmhamdi@gmail.com"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519
cat id_ed25519.pub
# https://github.com/settings/ssh/new



# compile neovim
# install depedencies
sudo apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip
sudo apt-get install -y nodejs
sudo apt-get install -y npm
sudo apt-get install -y python3-pip
sudo apt-get install -y python-pip
sudo apt-get install -y ripgrep fzf ranger

sudo pip install pynvim --user
sudo pip install neovim-remote
sudo pip install ueberzug

sudo npm install coc-explorer coc-snippets coc-json coc-actions --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod

#for coc
sudo pip3 install pynvim
sudo pip2 install pynvim
sudo pip  install pynvim
sudo npm install -g neovim

#fix yocompleme : run *.py
cd $HOME/.vim/bundle/youcompleteme
/usr/bin/python3 install.py 
export PYTHON_CONFIGURE_OPTS="--enable-framework"

#git
# neovim repository
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
git clone git@github.com:neovim/neovim.git ~/neovim
rm -r .config/nvim
git clone git@github.com:ayoubelmhamdi/nvim.git ~/.config/nvim
git clone git@github.com:ayoubelmhamdi/dotfiles-ayoub.git ~/dotfiles
.

#Compile neovim
cd ~/neovim
make CMAKE_BUILD_TYPE=Release
sudo make install




mkdir -p ~/.config/coc/extensions
cd ~/.config/coc/extensions
[ ! -f package.json ] && echo '{"dependencies":{}}'> package.json

nvim ~/.confi/nvim/Pluin/plugins.vim   +PluginInstall +qall






# 1. install zsh 
sudo apt-get zsh

# 2. install oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# 3. add plugin 
git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting


#dotfiles
git clone git@github.com:ayoubelmhamdi/dotfiles-ayoub.git

#tmux




cp $HOME/dotfiles/config-app/.* $HOME/


unzip
http://github.com/maxim-saplin/NetCoreStorageSpeedTest/releases/download/2.0.2-u/CPDT_Linux.zip
sudo apt-get install -y tmux
