#!/bin/bash

pkg=${@-}

if [[ $# == 0 ]];then
    echo -e '\ntrash-put \n\n\t$ trash-put --trash-dir=~/.Trash-0 foo\n\t$ rm foo'
elif [[ -s $1 ]];then
    trash-put --trash-dir=/root/.Trash-0 "$1" && echo "trash-rm $1"
else
    if [[ $# == 1 ]];then
        if [[ -z  $1 ]];then
            echo -e "\n$1 is empty"
        elif [[ ! -f  $1 ]];then
            echo -e "\n$1 is not exist"
            exit
        fi
    else
        echo -e "\nmulti file"
        echo "$@"
    fi
    echo -e '\nuse\n$ \\rm foo bar'
fi
