#!/bin/bash

linux="${1:-void}"

# if [[ -f /tmp/isload && "$(cat /tmp/isload)" == "y" ]];then
#   echo $isload
# else
  mount --rbind /sys /mnt/${linux}/sys && mount --make-rslave /mnt/${linux}/sys
  mount --rbind /dev /mnt/${linux}/dev && mount --make-rslave /mnt/${linux}/dev
  mount --rbind /proc /mnt/${linux}/proc && mount --make-rslave /mnt/${linux}/proc


  cat /etc/resolv.conf > /mnt/${linux}/etc/resolv.conf
# fi

chroot /mnt/${linux} /bin/bash
