#!/usr/bin/env bash

# NOTE:
# This doesn't work as is on Windows. You'll need to create an equivalent `.bat` file instead
#
# NOTE:
# If you're not using Linux you'll need to adjust the `-configuration` option
# to point to the `config_mac' or `config_win` folders depending on your system.

JAR="$HOME/.config/myConfig/jdtls-ayoub/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar"
GRADLE_HOME=$HOME/gradle /usr/lib/jvm/java-8-openjdk/bin/java \
  -Declipse.application=org.eclipse.jdt.ls.core.id1 \
  -Dosgi.bundles.defaultStartLevel=4 \
  -Declipse.product=org.eclipse.jdt.ls.core.product \
  -Dlog.protocol=true \
  -Dlog.level=ALL \
  -Xms1g \
  -Xmx2G \
  -jar $(echo "$JAR") \
  -configuration "$HOME/.config/coc/extensions/coc-java-data/server/config_linux" \
  -data "${1:-$HOME/workspace}"\ 
  # this for jdk 9+
  # --add-modules=ALL-SYSTEM \
  # --add-opens java.base/java.util=ALL-UNNAMED \
  # --add-opens java.base/java.lang=ALL-UNNAMED

